version: '3.7'
services:
  hyperf:
    image: "hyperf/biz-skeleton:latest"
    build:
      context: "."
    ports:
      - 8080:9501
    environment:
      APP_ENV: "${APP_ENV:-prod}"
    restart: "always"
    deploy:
      replicas: 1
